In [12]:
#importing basic necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
#loading data
df=pd.read_csv("data.csv")

In [14]:
#will have look at our data
df

timestamp equipment_energy_consumption     lighting_energy  \
0      2016-01-11 17:00:00                         60.0  -77.78778596503064   
1      2016-01-11 17:10:00                         60.0                30.0   
2      2016-01-11 17:20:00                         50.0                30.0   
3      2016-01-11 17:30:00                         50.0                40.0   
4      2016-01-11 17:40:00                         60.0                40.0   
...                    ...                          ...                 ...   
16852  2016-10-03 20:10:00           1139.9856929495108                20.0   
16853  2016-10-04 06:10:00                         50.0   86.00296632575207   
16854  2016-11-03 00:50:00                         50.0                 0.0   
16855  2016-11-04 13:20:00                         80.0                 0.0   
16856  2016-12-01 15:50:00                         30.0                 0.0   

        zone1_temperature      zone1_humidity   zone2_temperature  \
0       33.74660933896648   47.59666666666671                19.2   
1                   19.89   46.69333333333329                19.2   
2                   19.89                46.3                19.2   
3       33.74660933896648    46.0666666666667                19.2   
4                   19.89   46.33333333333329                19.2   
...                   ...                 ...                 ...   
16852                22.1  38.723333333333294               19.79   
16853               21.29    39.6266666666667                18.1   
16854               21.39               37.59  18.463333333333296   
16855                22.5               39.36                23.6   
16856  20.066666666666695  43.863333333333294    19.1333333333333   

       zone2_humidity  zone3_temperature  zone3_humidity  zone4_temperature  \
0           44.790000              19.79             NaN          19.000000   
1           44.722500              19.79       44.790000          19.000000   
2           44.626667              19.79       44.933333          35.921144   
3           44.590000              19.79       45.000000                NaN   
4           44.530000              19.79       45.000000          18.890000   
...               ...                ...             ...                ...   
16852       39.566667              21.29       38.845000          21.390000   
16853       44.290000              22.39       38.760000                NaN   
16854       39.966667              21.10       37.790000          20.600000   
16855       35.730000              23.10       38.000000          22.290000   
16856       42.863333              19.89       44.760000          19.600000   

       ...  zone9_temperature  zone9_humidity  outdoor_temperature  \
0      ...          17.033333           45.53             6.600000   
1      ...          17.066667           45.56             6.483333   
2      ...          17.000000           45.50             6.366667   
3      ...          17.000000           45.40             6.250000   
4      ...           4.476511           45.40             6.133333   
...    ...                ...             ...                  ...   
16852  ...          18.100000           40.09             5.816667   
16853  ...          20.200000           44.50             3.683333   
16854  ...          18.100000           40.20             1.750000   
16855  ...          21.100000           39.53            16.800000   
16856  ...          17.166667           43.79             6.400000   

       atmospheric_pressure  outdoor_humidity  wind_speed  visibility_index  \
0                733.500000         92.000000    7.000000         63.000000   
1                733.600000         92.000000    6.666667         59.166667   
2                733.700000         92.000000    6.333333         55.333333   
3                733.800000         92.000000    6.000000         51.500000   
4                733.900000         92.000000    5.666

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16857 entries, 0 to 16856
Data columns (total 29 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   timestamp                     16857 non-null  object 
 1   equipment_energy_consumption  16013 non-null  object 
 2   lighting_energy               16048 non-null  object 
 3   zone1_temperature             15990 non-null  object 
 4   zone1_humidity                16056 non-null  object 
 5   zone2_temperature             16004 non-null  object 
 6   zone2_humidity                15990 non-null  float64
 7   zone3_temperature             16055 non-null  float64
 8   zone3_humidity                15979 non-null  float64
 9   zone4_temperature             16041 non-null  float64
 10  zone4_humidity                16076 non-null  float64
 11  zone5_temperature             16019 non-null  float64
 12  zone5_humidity                16056 non-null  float64
 13  z

In [16]:
#we can see top 6 cols are object and we also need to separate time stamp data

In [17]:
#We will work on each colum one by one first lets separate data from timestamp
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Extract components

df['day'] = df['timestamp'].dt.day
df['month'] = df['timestamp'].dt.month
df['year'] = df['timestamp'].dt.year
df['hour'] = df['timestamp'].dt.hour
df['minute'] = df['timestamp'].dt.minute
df['second'] = df['timestamp'].dt.second
#will drop timestamp as it is no longer required
df.drop("timestamp",axis=1,inplace=True)

In [18]:
#while going through the data i saw the year is 2016 at most of the places.i need to check if it is constant then we need to remove such data

In [19]:
#lets check the uniqueness

In [20]:
df.year.unique()

array([2016], dtype=int32)

In [21]:
#see only value present is 2016 so we can drop this 

In [23]:
df.drop("year",inplace=True,axis=1)

In [24]:
#now lets check for other cols that we separated 

In [25]:
df.day.unique()

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
      dtype=int32)

In [26]:
df.month.unique()

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12], dtype=int32)

In [27]:
df.second.unique()

array([0], dtype=int32)

In [28]:
#need to drop above col too as it only has value 0

In [29]:
df.drop("second",inplace=True,axis=1)

In [30]:
df.minute.unique()

array([ 0, 10, 20, 30, 40, 50], dtype=int32)

In [31]:
df.hour.unique()

array([17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16], dtype=int32)

In [32]:
#lets have a look at data again
df.head(2)

equipment_energy_consumption     lighting_energy  zone1_temperature  \
0                         60.0  -77.78778596503064  33.74660933896648   
1                         60.0                30.0              19.89   

      zone1_humidity zone2_temperature  zone2_humidity  zone3_temperature  \
0  47.59666666666671              19.2         44.7900              19.79   
1  46.69333333333329              19.2         44.7225              19.79   

   zone3_humidity  zone4_temperature  zone4_humidity  ...  outdoor_humidity  \
0             NaN               19.0       45.566667  ...              92.0   
1           44.79               19.0       45.992500  ...              92.0   

   wind_speed  visibility_index  dew_point  random_variable1  \
0    7.000000         63.000000        5.3         13.275433   
1    6.666667         59.166667        5.2         18.606195   

   random_variable2  day  month  hour  minute  
0         13.275433   11      1    17       0  
1         18.606195   11      1    17      10  

[2 rows x 32 columns]

In [33]:
#we still need to work on cols which have object data type

In [34]:
#lets work on equipment_energy_consumption

In [35]:
df.equipment_energy_consumption.unique()

array(['60.0', '50.0', nan, '70.0', '230.0', '580.0', '430.0', '250.0',
       '100.0', '90.0', '80.0', '140.0', '120.0', '190.0', '110.0',
       '400.0', '390.0', '240.0', '40.0', '30.0', '310.0', '380.0',
       '370.0', '20.0', '-110.0', '260.0', '500.0', '450.0', '220.0',
       '170.0', '290.0', '130.0', '200.0', '210.0', '-50.0', '-20.0',
       '-944.5664110012307', '350.0', '300.0', '-400.0', '340.0', '150.0',
       '330.0', '420.0', '520.0', '360.0', '-270.0', '-30.0', '180.0',
       '550.0', '690.0', '620.0', '610.0', '490.0', '410.0', '320.0',
       '270.0', '740.0', '910.0', '510.0', '790.0', '1139.9856929495108',
       '-40.0', 'error', '460.0', '160.0', '480.0', '280.0', '-220.0',
       '560.0', '1080.0', '750.0', '???', '470.0', '440.0', '-80.0',
       '800.0', '-790.0', '540.0', '530.0', 'check', '660.0', '630.0',
       '600.0', '10.0', '570.0', '830.0', '1070.0', '890.0', '590.0',
       '-1139.9856929495108', '850.0', '710.0', '680.0', '-120.0',
       '-310.0

In [36]:
# i can see there are -ve as well as unknown values

In [37]:
df['equipment_energy_consumption'] = pd.to_numeric(df['equipment_energy_consumption'], errors='coerce')

In [38]:
#above line will covert data which is numeric to float and data which is non numeric like unknown as NaN

In [39]:
df.equipment_energy_consumption.unique()

array([   60.        ,    50.        ,            nan,    70.        ,
         230.        ,   580.        ,   430.        ,   250.        ,
         100.        ,    90.        ,    80.        ,   140.        ,
         120.        ,   190.        ,   110.        ,   400.        ,
         390.        ,   240.        ,    40.        ,    30.        ,
         310.        ,   380.        ,   370.        ,    20.        ,
        -110.        ,   260.        ,   500.        ,   450.        ,
         220.        ,   170.        ,   290.        ,   130.        ,
         200.        ,   210.        ,   -50.        ,   -20.        ,
        -944.566411  ,   350.        ,   300.        ,  -400.        ,
         340.        ,   150.        ,   330.        ,   420.        ,
         520.        ,   360.        ,  -270.        ,   -30.        ,
         180.        ,   550.        ,   690.        ,   620.        ,
         610.        ,   490.        ,   410.        ,   320.        ,
      

In [40]:
#now i dont see any non-numeric data

In [41]:
#lets check how many nan values are there

In [42]:
df.equipment_energy_consumption.isnull().sum()

np.int64(912)

In [43]:
#equipment_energy_consumption this is our target feature so we will simply remove records with nan values as they are not of any use

In [44]:
#and one more thing to notice energy consumption cant be -ve so i am removing that too

In [45]:
(df['equipment_energy_consumption'] < 0).sum()

np.int64(314)

In [46]:
df = df[df['equipment_energy_consumption'].notna() & (df['equipment_energy_consumption'] >= 0)]

In [47]:
df.shape

(15631, 32)

In [48]:
#we removed few records

In [49]:
df.describe()

equipment_energy_consumption  zone2_humidity  zone3_temperature  \
count                  15631.000000    14828.000000       14886.000000   
mean                     108.584711       39.501397          21.669488   
std                      148.628836       10.044737           2.603906   
min                       10.000000      -77.265503           6.543921   
25%                       50.000000       37.745000          20.533333   
50%                       60.000000       40.290000          21.790000   
75%                      100.000000       43.000000          22.763333   
max                     1139.985693       77.265503          36.823982   

       zone3_humidity  zone4_temperature  zone4_humidity  zone5_temperature  \
count    14823.000000       14873.000000    14911.000000       14860.000000   
mean        38.176231          20.238371       37.925650          19.053025   
std         10.155610           2.803067       10.766489           2.348941   
min        -71.406273           4.613485      -81.446225           5.921094   
25%         36.626667          19.263333       35.188810          18.066667   
50%         38.400000          20.290000       38.090000          19.071825   
75%         41.412500          21.375714       41.545000          20.100000   
max         71.406273          35.921144       81.446225          32.157594   

       zone5_humidity  zone6_temperature  zone6_humidity  ...  \
count    14897.000000       14844.000000    14850.000000  ...   
mean        50.333011           6.500785       59.134224  ...   
std         18.857234           8.827877       52.383943  ...   
min       -141.640143         -42.987365     -353.393026  ...   
25%         45.290000           2.929167       36.997500  ...   
50%         48.826667           6.263333       62.553333  ...   
75%         53.930000           9.690000       86.590000  ...   
max        141.640143          55.932271      353.393026  ...   

       outdoor_humidity    wind_speed  visibility_index     dew_point  \
count      14893.000000  14867.000000      14883.000000  14881.000000   
mean          79.033698      4.182040         38.412814      2.771432   
std           28.399240      4.419638         21.411845      6.047731   
min         -221.668765    -20.929527        -82.329792    -32.098095   
25%           71.000000      2.000000         29.000000      0.450000   
50%           84.166667      4.000000         40.000000      2.766667   
75%           91.904762      6.000000         40.000000      5.300000   
max          221.668765     29.318719        159.606156     37.673716   

       random_variable1  random_variable2           day         month  \
count      14858.000000      14867.000000  15631.000000  15631.000000   
mean          24.824855         25.146877     15.853880      2.774231   
std           26.269840         25.574001      8.801908      1.178889   
min         -120.170177       -120.409590      1.000000      1.000000   
25%           12.174779         12.229145      8.000000      2.000000   
50%           24.883977         24.905165     16.000000      3.000000   
75%           37.977137         38.025468     23.000000      4.000000   
max          170.156325        170.329617     31.000000     12.000000   

               hour        minute  
count  15631.000000  15631.000000  
mean      11.489796     25.006078  
std        6.935283     17.102256  
min        0.000000      0.000000  
25%        5.000000     10.000000  
50%       11.000000     30.000000  
75%       17.500000     40.000000  
max       23.000000     50.000000  

[8 rows x 28 columns]

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15631 entries, 0 to 16856
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   equipment_energy_consumption  15631 non-null  float64
 1   lighting_energy               14896 non-null  object 
 2   zone1_temperature             14829 non-null  object 
 3   zone1_humidity                14884 non-null  object 
 4   zone2_temperature             14839 non-null  object 
 5   zone2_humidity                14828 non-null  float64
 6   zone3_temperature             14886 non-null  float64
 7   zone3_humidity                14823 non-null  float64
 8   zone4_temperature             14873 non-null  float64
 9   zone4_humidity                14911 non-null  float64
 10  zone5_temperature             14860 non-null  float64
 11  zone5_humidity                14897 non-null  float64
 12  zone6_temperature             14844 non-null  float64
 13  zone6_

In [51]:
#we still need to work on those 4 cols which have object dtype

In [52]:
#will do same process for other cols

In [53]:
df['lighting_energy'] = pd.to_numeric(df['lighting_energy'], errors='coerce')

C:\Users\bhatk\AppData\Local\Temp\ipykernel_15112\1034915347.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lighting_energy'] = pd.to_numeric(df['lighting_energy'], errors='coerce')


In [54]:
df.lighting_energy.isnull().sum()

np.int64(787)

In [55]:
(df['lighting_energy'] < 0).sum()

np.int64(216)

In [56]:
df = df[(df['lighting_energy'] >= 0)]

In [57]:
df.shape

(14628, 32)

In [58]:
df.lighting_energy.value_counts()

lighting_energy
0.000000     10968
10.000000     1750
20.000000     1245
30.000000      436
86.002966      156
40.000000       65
50.000000        6
60.000000        1
70.000000        1
Name: count, dtype: int64

In [59]:
#we dont have -ve vaalue now for energy

In [61]:
df['zone1_temperature'] = pd.to_numeric(df['zone1_temperature'], errors='coerce')
df.zone1_temperature.isnull().sum()

np.int64(823)

In [62]:
df['zone1_humidity'] = pd.to_numeric(df['zone1_humidity'], errors='coerce')
df.zone1_humidity.isnull().sum()

np.int64(770)

In [63]:
(df['zone1_humidity'] < 0).sum()

np.int64(129)

In [71]:
# as i saw most of cols have -ve values but when i went thrugh the data i felt like this is basically a data entry mistake (i am deciding to remove -ve sign)

In [72]:
#some cols cant be -ve like beow

In [73]:
non_negative_cols=["equipment_energy_consumption","lighting_energy","zone1_humidity","zone2_humidity","zone3_humidity","zone4_humidity",
                   "zone5_humidity","zone6_humidity","zone7_humidity","zone8_humidity","zone9_humidity","atmospheric_pressure",
                   "outdoor_humidity","wind_speed","visibility_index"
                  ]


In [74]:
df[non_negative_cols] = df[non_negative_cols].abs()

In [75]:
#lets check if we have -ve values

In [76]:
(df['zone1_humidity'] < 0).sum()

np.int64(0)

In [77]:
(df['zone3_humidity'] < 0).sum()

np.int64(0)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14628 entries, 1 to 16856
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   equipment_energy_consumption  14628 non-null  float64
 1   lighting_energy               14628 non-null  float64
 2   zone1_temperature             13805 non-null  float64
 3   zone1_humidity                13858 non-null  float64
 4   zone2_temperature             13890 non-null  object 
 5   zone2_humidity                13865 non-null  float64
 6   zone3_temperature             13937 non-null  float64
 7   zone3_humidity                13869 non-null  float64
 8   zone4_temperature             13912 non-null  float64
 9   zone4_humidity                13956 non-null  float64
 10  zone5_temperature             13910 non-null  float64
 11  zone5_humidity                13932 non-null  float64
 12  zone6_temperature             13888 non-null  float64
 13  zone6_

In [79]:
#lets change zone2 temperature

In [80]:
df['zone2_temperature'] = pd.to_numeric(df['zone2_temperature'], errors='coerce')


In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14628 entries, 1 to 16856
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   equipment_energy_consumption  14628 non-null  float64
 1   lighting_energy               14628 non-null  float64
 2   zone1_temperature             13805 non-null  float64
 3   zone1_humidity                13858 non-null  float64
 4   zone2_temperature             13829 non-null  float64
 5   zone2_humidity                13865 non-null  float64
 6   zone3_temperature             13937 non-null  float64
 7   zone3_humidity                13869 non-null  float64
 8   zone4_temperature             13912 non-null  float64
 9   zone4_humidity                13956 non-null  float64
 10  zone5_temperature             13910 non-null  float64
 11  zone5_humidity                13932 non-null  float64
 12  zone6_temperature             13888 non-null  float64
 13  zone6_

In [82]:
#now evrything is numeric and we also have dealth with -ve values 